#!/usr/bin/env python3
"""Builds the offline Pokedex site in tools/dex_site/ from the ROM data.

First runs the three export scripts (skip them with --no-export), then reads their JSON files:
  tools/export_pokemon_json/pokemon.json
  tools/export_moves_json/moves.json
  tools/export_abilities_json/abilities.json
plus, straight from the sources:
  src/battle_main.c               type chart (gTypeEffectiveness)
  include/constants/tms_hms.h     TM/HM numbers
  graphics/pokemon/*/front.png    sprites (copied to sprites/pokemon/N.png)
and writes js/data.js, which holds all the data so that index.html works by just opening it
in the browser (file://, no server needed).

Usage (Pillow is needed for the sprites: sudo apt install python3-pil):
  python3 tools/dex_site/build.py [--no-export] [--no-sprites]
then open tools/dex_site/index.html in the browser.
"""
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
TOOLS = os.path.join(ROOT, 'tools')

MULTIPLIERS = {'TYPE_MUL_SUPER_EFFECTIVE': 2, 'TYPE_MUL_NOT_EFFECTIVE': 0.5, 'TYPE_MUL_NO_EFFECT': 0}


def read(path):
    with open(os.path.join(ROOT, path), encoding='utf-8') as f:
        return f.read()


def load_json(path):
    with open(os.path.join(TOOLS, path), encoding='utf-8') as f:
        return json.load(f)


def parse_type_chart():
    text = read('src/battle_main.c')
    table = re.search(r'gTypeEffectiveness\[\d*\] =\s*\{(.*?)\};', text, re.S).group(1)
    chart = {}
    for atk, dfn, mul in re.findall(r'TYPE_(\w+), TYPE_(\w+), (TYPE_MUL_\w+)', table):
        if atk in ('FORESIGHT', 'ENDTABLE'):
            continue  # markers, not real entries (Normal/Fighting vs Ghost come after FORESIGHT)
        chart.setdefault(atk, {})[dfn] = MULTIPLIERS[mul]
    return chart


def parse_tms():
    text = read('include/constants/tms_hms.h')
    tms = {}
    for macro, prefix in (('FOREACH_TM', 'TM'), ('FOREACH_HM', 'HM')):
        body = re.search(r'#define %s\(F\)(.*?)\n\n' % macro, text, re.S).group(1)
        for i, move in enumerate(re.findall(r'F\((\w+)\)', body), 1):
            tms[move] = f'{prefix}{i:02d}'
    return tms


def copy_sprites(pokemon):
    try:
        from PIL import Image
    except ImportError:
        print('Pillow is not installed: sprites skipped (sudo apt install python3-pil)')
        return
    out_dir = os.path.join(HERE, 'sprites', 'pokemon')
    os.makedirs(out_dir, exist_ok=True)
    missing = []
    for p in pokemon:
        folder = os.path.join(ROOT, 'graphics', 'pokemon', p['species'].lower())
        for form in ('a', 'normal'):  # Unown and Castform keep each form in a subfolder
            if os.path.isdir(os.path.join(folder, form)):
                folder = os.path.join(folder, form)
        src = os.path.join(folder, 'front.png')
        if not os.path.exists(src):
            missing.append(p['species'])
            continue
        img = Image.open(src)
        img = img.crop((0, 0, 64, 64))  # some sheets hold several frames or forms
        rgba = img.convert('RGBA')
        if img.mode == 'P':
            # colour 0 of the palette is the transparent background
            mask = img.point(lambda i: 0 if i == 0 else 255, 'L')
            rgba.putalpha(mask)
        rgba.save(os.path.join(HERE, p['_sprite']))
    print(f'{len(pokemon) - len(missing)} sprites written to {out_dir}')
    if missing:
        print('Sprites not found:', ', '.join(missing))


def run_exporters():
    for script in ('export_pokemon_json', 'export_moves_json', 'export_abilities_json'):
        subprocess.run([sys.executable, os.path.join(TOOLS, script, script + '.py')], cwd=ROOT, check=True)


def main():
    if '--no-export' not in sys.argv:
        run_exporters()
    pokemon = load_json('export_pokemon_json/pokemon.json')
    moves = load_json('export_moves_json/moves.json')
    abilities = load_json('export_abilities_json/abilities.json')
    chart = parse_type_chart()
    tms = parse_tms()

    out = os.path.join(HERE, 'js', 'data.js')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* js/data.js - generated by tools/dex_site/build.py, do not edit */\n')
        for name, value in (('RAW_POKEMON', pokemon), ('RAW_MOVES', moves), ('RAW_ABILITIES', abilities),
                            ('TYPE_CHART', chart), ('TM_NUMBERS', tms)):
            f.write(f'const {name} = {json.dumps(value, ensure_ascii=False)};\n')
    print(f'{len(pokemon)} Pokemon, {len(moves)} moves, {len(abilities)} abilities, '
          f'{len(tms)} TM/HM written to {out}')

    if '--no-sprites' not in sys.argv:
        copy_sprites(pokemon)


if __name__ == '__main__':
    main()
